classes: {
    blue: {
      label: "Code version N "
      shape: rectangle
      width: 80
      height: 200
      style: {
        shadow: true
        fill: "#4f4fff"
      }
    }
    green: {
      label: "Code version N+1 "
      shape: rectangle
      width: 80
      height: 200
      style: {
        shadow: true
        fill: "#84f4cd"
      }
    }
  }
  
  router: Router
  
  app: "" {
    blue: "Blue" {
      blue1
      blue2
      blue3
    }
    green: "Green" {
      green1
      green2
      green3
    }
  }
  
  router -> app.green
  
  router -> app.blue: {
    style: {
      stroke-dash: 3
    }
  }
  
  app.blue.blue1.class: blue
  app.blue.blue2.class: blue
  app.blue.blue3.class: blue
  
  app.green.green1.class: green
  app.green.green2.class: green
  app.green.green3.class: green
  
  title: Switching from Blue to Green {
    shape: text
    near: bottom-center
    style: {
      font-size: 24
      italic: true
    }
  }
  