classes: {
    dev: {
      label: "Dev environment"
      shape: rectangle
  
      style: {
        shadow: true
        fill: yellow
      }
    }
    git: {
      label: "GitHub"
      shape: rectangle
  
      style: {
        shadow: true
        fill: "#84f4cd"
      }
    }
    actions: {
      label: "GitHub Actions"
      shape: rectangle
  
      style: {
        shadow: true
        fill: red
      }
    }
    argo: {
      label: "Argo CD"
      shape: rectangle
  
      style: {
        fill: "#f4a261"
        border-radius: 10
        3d: false
      }
    }
    helm: {
      label: "Helm"
      shape: rectangle
  
      style: {
        fill: "#f4a261"
        border-radius: 10
        3d: false
      }
    }
    docker: {
      label: "Docker Hub"
      shape: rectangle
      style: {
        fill: "#f4a261"
        border-radius: 10
        3d: false
      }
    }
    kube: {
      label: "Kubernetes cluster"
      shape: rectangle
  
      style: {
        shadow: true
        fill: yellow
      }
    }
  }
  
  dev -> git: (1) Changes pushed
  git -> actions: (2) Actions triggered (unit tests..etc)
  actions -> docker: (3) Docker image pushed
  actions -> helm: (4) Helm release created
  helm -> git: (5) Helm release pushed (GH Pages)
  git -> argo: (6) New release detected
  docker -> argo: (7) Latest image pulled
  argo -> kube: (8) Latest changes deployed
  
  dev.class: dev
  git.class: git
  actions.class: actions
  argo.class: argo
  helm.class: helm
  docker.class: docker
  kube.class: kube
  
  title: CI/CD with GitOps, GitHub, Argo CD and Helm {
    shape: text
    near: bottom-center
    style: {
      font-size: 45
      italic: true
    }
  }
  