cluster: Cluster {
  client: Client
  clusterIP: ClusterIP
  pod_1: Pod
  pod_2: Pod
  pod_3: Pod
}

cluster.client -> cluster.clusterip: Traffic
cluster.clusterip -> cluster.pod_1
cluster.clusterip -> cluster.pod_2
cluster.clusterip -> cluster.pod_3

title: ClusterIP Service {
  shape: text
  near: bottom-center
  style: {
    font-size: 24
    italic: true
  }
}

