classes: {
  tainted: {
    label: "Tainted Node"
    shape: rectangle
    width: 80
    height: 200
    style: {
      shadow: true
      fill: "#f72714"
    }
  }
  untainted: {
    label: "Node"
    shape: rectangle
    width: 80
    height: 200
    style: {
      shadow: true
      fill: green
    }
  }
}

cluster: Cluster {
  node1: Node A {
    nopod: DaemonSet Pod
  }
  node2: Node B {
    pod1: DaemonSet Pod
  }
  node3: Node C {
    pod2: DaemonSet Pod
  }
}

cluster.node1.class: untainted
cluster.node2.class: untainted
cluster.node3.class: untainted

daemonsetcontroller: DaemonSet Controller
daemonsetcontroller -> cluster.node1
daemonsetcontroller -> cluster.node2
daemonsetcontroller -> cluster.node3

title: Our DaemonSet Controller ensures that all Nodes run a copy of the Pod {
  shape: text
  near: bottom-center
  style: {
    font-size: 24
    italic: true
  }
}
