client: Client
cluster: Cluster {
  service: Ingress
  service_1: Service
  service_2: Service
  service_3: Service

  pod_1: Pod
  pod_2: Pod
  pod_3: Pod
  pod_4: Pod
  pod_5: Pod
  pod_6: Pod
}

client -> cluster.service.adress_1: Traffic
client -> cluster.service.adress_2
client -> cluster.service.adress_3: Traffic

cluster.service.adress_1 -> cluster.service_1
cluster.service.adress_2 -> cluster.service_2
cluster.service.adress_3 -> cluster.service_3

cluster.service_1 -> cluster.pod_1
cluster.service_1 -> cluster.pod_2
cluster.service_2 -> cluster.pod_3
cluster.service_2 -> cluster.pod_4
cluster.service_3 -> cluster.pod_5
cluster.service_3 -> cluster.pod_6

cluster.service: {
  adress_1: subdomain.domain.tld
  adress_2: domain.tld/path
  adress_3: another-domain.tld
}

title1: Kubernetes Ingress {
  shape: text
  near: bottom-center
  style: {
    font-size: 43
    italic: true
  }
}

