client: Client
lb: Load Balancer

cluster: Cluster {
  service: Service
  pod_1: Pod
  pod_2: Pod
  pod_3: Pod
}

client -> lb: Traffic
lb -> cluster.service

cluster.service -> cluster.pod_1
cluster.service -> cluster.pod_2
cluster.service -> cluster.pod_3

title1: Kubernetes Load Balancer {
  shape: text
  near: bottom-center
  style: {
    font-size: 43
    italic: true
  }
}
