client: Client
node_1: Node {
  port_1: port 5000
}
node_2: Node {
  port_2: port 5000
}

cluster: Cluster {
  service: NodePort Service
  pod_1: Pod
  pod_2: Pod
  pod_3: Pod
}

client -> node_1.port_1: Traffic
node_1.port_1 -> cluster.service
client -> node_2.port_2: Traffic
node_2.port_2 -> cluster.service
cluster.service -> cluster.pod_1
cluster.service -> cluster.pod_2
cluster.service -> cluster.pod_3

title1: Kubernetes NodePort {
  shape: text
  near: bottom-center
  style: {
    font-size: 43
    italic: true
  }
}

