classes: {
  app: {
    label: "Application"
    shape: rectangle
    width: 500
    height: 500
    style: {
      double-border: true
      shadow: true
      fill: "#e5b94b"
      font-color: white
      font-size: 40
    }
  }
  otel: {
    label: "OTel Collector"
    shape: square
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#0facf3"
      font-color: white
      font-size: 40
    }
  }
  db: {
    label: "Datastore/Memory"
    shape: square
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      # fill: "#0facf3"
      # font-color: white
      font-size: 40
    }
  }
  ja1: {
    label: "Jaeger Collector"
    shape: square
    # near: 
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#ff6a07"
      font-color: white
      font-size: 40
    }
  }
  ja2: {
    label: "Jaeger Query"
    shape: square
    # near: 
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#ff6a07"
      font-color: white
      font-size: 40
    }
  }
  ja3: {
    label: "Jaeger UI"
    shape: square
    # near: 
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#ff6a07"
      font-color: white
      font-size: 40
    }
  }
}

app.class: app
app.otel.class: otel
db.class: db
ja1.class: ja1
ja2.class: ja2
ja3.class: ja3

app: {
  otel
}
app.otel -> ja1: push {
  style: {
    font-size: 50
  }
}
ja1 -> db
db -> ja2
ja2 -> ja3

title1: OpenTelemetry Auto Instrumentation and Jaeger {
  shape: text
  near: bottom-center
  style: {
    font-size: 70
    italic: true
  }
}