classes: {
  logs: {
    label: "Logs"
    shape: circle
    width: 300
    height: 300
    style: {
      # double-border: true
      # shadow: true
      # fill: "#e5b94b"
      # font-color: white
      font-size: 40
    }
  }
  promtail: {
    label: "Promtail"
    shape: rectangle
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#e5b94b"
      font-color: white
      font-size: 40
    }
  }
  loki: {
    label: "Loki"
    shape: square
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#0facf3"
      font-color: white
      font-size: 40
    }
  }
  grafana: {
    label: "Grafana"
    shape: square
    # near: 
    width: 300
    height: 300
    style: {
      double-border: true
      shadow: true
      fill: "#ff6a07"
      font-color: white
      font-size: 40
    }
  }
}

logs.class: logs
promtail.class: promtail
loki.class: loki
grafana.class: grafana

logs -> promtail: Collect {
  style: {
    font-size: 40
  }
}
promtail -> loki: Process {
  style: {
    font-size: 40
  }
}
loki -> grafana: Visualize {
  style: {
    font-size: 40
  }
}

title1: A 3-components Loki-based logging stack {
  shape: text
  near: bottom-center
  style: {
    font-size: 43
    italic: true
  }
}
