classes: {
  master: {
    label: "Master"
    shape: rectangle
    width: 80
    height: 100
    style: {
      shadow: false
      fill: yellow
    }
  }
  replica: {
    label: "Replica"
    shape: rectangle
    width: 80
    height: 200
    style: {
      shadow: false
      fill: "#f72714"
    }
  }
}

cluster: PostgreSQL cluster {
  master
  replica1: replica
  replica2: replica
  replica3: replica
}

cluster.master.class: master
cluster.replica1.class: replica
cluster.replica2.class: replica
cluster.replica3.class: replica

cluster.master -> cluster.replica1: replication
cluster.master -> cluster.replica2: replication
cluster.master -> cluster.replica3: replication

app: Application
app -> cluster: ADD, REMOVE, UPDATE..etc

title: PostgreSQL Replication {
  shape: text
  near: bottom-center
  style: {
    font-size: 43
    italic: true
  }
}

