metric_server: Metric Server

vpa: Virtual Pod Autoscaler

pod: Pod
pod_s: Scale down
pod_l: Scale up

metric_server -> vpa -> pod

pod -> pod_s
pod -> pod_l

title: Kubernetes Vertical Autoscaling {
  shape: text
  near: bottom-center
  style: {
    font-size: 24
    italic: true
  }
}

