classes: {
  limit50: {
    label: "Limits"
    shape: rectangle
    width: 80
    height: 100
    style: {
      shadow: false
      fill: yellow
    }
  }
  request50: {
    label: "Requests"
    shape: rectangle
    width: 80
    height: 100
    style: {
      shadow: false
      fill: yellow
    }
  }
  request100: {
    label: "Requests"
    shape: rectangle
    width: 80
    height: 200
    style: {
      shadow: false
      fill: "#f72714"
    }
  }
  limit100: {
    label: "Limits"
    shape: rectangle
    width: 80
    height: 200
    style: {
      shadow: false
      fill: "#f72714"
    }
  }
}

first: Initial state {
  request50: Initial request
  limit50: Initial limit
}

second: Final state {
  request100: Initial request
  limit100: Initial limit
}

first.request50.class: request50
first.limit50.class: limit50

second.request100.class: request100
second.limit100.class: limit100

vpa: Vertical Pod Autoscaler
metrics: Metrics

first -> metrics: Get metrics
first -> second: Scale up

metrics -> vpa: Send metrics
vpa -> first: Kill and recreate

title: Kubernetes VPA Scaling up {
  shape: text
  near: bottom-center
  style: {
    font-size: 44
    italic: true
  }
}

