classes: {
  black: {
    label: "Blackbox"
    shape: rectangle
    width: 580
    height: 200
    style: {
      double-border: true
      shadow: true
      fill: "#b7c7e0"
      font-size: 42
      font-color: black
    }
  }
  white: {
    label: "Whitebox"
    shape: rectangle
    width: 580
    height: 200
    style: {
      double-border: true
      shadow: true
      fill: "#efefef"
      font-size: 42
      font-color: black
    }
  }
  a: {
    label: ""
    height: 200
  }
  b: {
    label: ""
    height: 200
  }
}

black.class: black
white.class: white
a.class: a
b.class: b

black: {
  text1: |md
    Polling / Uptime / Monitoring
  |
}

white: {
  text2: |md
    Metrics / Logs/ Tracing
  |
}

a.Active
a.Cause
a.Predictive
a.Code change required
b.Passive
b.Symptom
b.Descriptive
b.No code change required

a.Active.style.font-size: 40
a.Cause.style.font-size: 40
a.Predictive.style.font-size: 40
a.Code change required.style.font-size: 40
b.Passive.style.font-size: 40
b.Symptom.style.font-size: 40
b.Descriptive.style.font-size: 40
b.No code change required.style.font-size: 40

black -> b
white -> a

title: Blackbox vs. Whitebox monitoring {
  shape: text
  near: bottom-center
  style: {
    font-size: 44
    italic: true
  }
}

black.text1.style.font-size: 32
white.text2.style.font-size: 32